#-*- coding:utf-8 -*-
# /usr/bin/python
# merge two json files generated by LABELME to avoid repeated tags.

'''
File Tree:
.
|-merge_json.py
|-test
    |-0030
        |-depth
            |-30_depth_0.npy
            |-...
        |-RGB
        |-30_RGB_0.jpg
        |-30_RGB_0.json
        |-...
    |-0031
        |-...
'''

import os
import json

PREVIOUS_DIRECTORY = None
CURRENT_DIRECTORY = None
COLORMAP={"yellow_cube":{"lineColor": [0, 255, 0, 128], "fillColor": [255, 0, 0, 128]}
}

for dirs in os.listdir('./test'):
    if CURRENT_DIRECTORY is None:
        PREVIOUS_DIRECTORY = None
        CURRENT_DIRECTORY = os.path.join('test', dirs, 'RGB')
        continue
    else:
        PREVIOUS_DIRECTORY = CURRENT_DIRECTORY
        CURRENT_DIRECTORY = os.path.join('test', dirs, 'RGB') 
        # main loop
        for file in os.listdir(CURRENT_DIRECTORY):
            if(os.path.splitext(file)[1] != '.json'):
                continue
            else:
                previous_file_name = os.path.join(PREVIOUS_DIRECTORY, file)
                current_file_name = os.path.join(CURRENT_DIRECTORY, file)

                previous_file = json.loads(open(previous_file_name, 'r').read())
                current_file = json.loads(open(current_file_name, 'r').read())

                previous_file['shapes'].extend(current_file['shapes'])
                current_file['shapes']  = previous_file['shapes']

                with open(current_file_name+'.test', 'w') as f:
                    json.dump(current_file, f, indent=1)
                    print(current_file_name+'.test' + " Finished!")
